### ISSUE TITLE
need an update for mips changes in the recent game update

### ISSUE THREAD

**Issue by JaysonPhoenix** [Stationeers-ic/Ic10-and-Icx-Sample#1]
after the recent stationeers update your script needs an update to integrate the changes made to the games mips. thx in advance, appreciate your script, a lot ;)

edit:
just realized vsc sent me to the wrong git to create an issue report, i guess vscode-stationeers-ic10 would have been the right one since somebody already created an issue report for the problem there, so sry if this was the wrong place

**Comment by Traineratwot** [comment]
I update vs code plugin tri it :)

https://marketplace.visualstudio.com/items?itemName=Traineratwot.stationeers-ic10
